apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "home-assistant.name" . }}
    helm.sh/chart: {{ include "home-assistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "home-assistant.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "home-assistant.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "home-assistant.fullname" . }}-api-token
                  key: token
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: storage-volume
              mountPath: /config
            {{- range $key, $value := .Values.serverFiles }}
            - name: config-volume
              mountPath: "/config/{{ $key }}"
              subPath: "{{ $key }}"
            {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "home-assistant.fullname" . }}-config
      - name: storage-volume
    {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
        {{- if .Values.persistentVolume.existingClaim -}}
          claimName: {{ .Values.persistentVolume.existingClaim }}
        {{ else }}
          claimName: {{ include "home-assistant.fullname" . }}
        {{- end }}
    {{- else }}
        emptyDir: {}
    {{- end -}}