apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}-api-token
type: Opaque
data:
  {{- if .Values.apiToken -}}
  token: "{{ .Values.apiToken | b64enc }}"
  {{ else }}
  token: "{{ randAlphaNum 20 | b64enc }}"
  {{- end -}}