apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "azure-devops-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
    helm.sh/chart: {{ include "azure-devops-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "azure-devops-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VSTS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-agent-secret
                  key: azureToken
            - name: VSTS_ACCOUNT
              value: {{ .Values.azure.account }}
            - name: VSTS_POOL
              value: {{ .Values.azure.agentPool | default "Default" }}
            - name: VSTS_AGENT
              value: {{ .Values.azure.agentName | default "$HOSTNAME" }}
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: false
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
