apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "homeassistant.name" . }}
    helm.sh/chart: {{ include "homeassistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homeassistant.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homeassistant.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-configurator
          image: "{{ .Values.image.configurator.repository }}:{{ .Values.image.configurator.tag}}"
          imagePullPolicy: {{ .Values.image.configurator.pullPolicy }}
          env:
            - name: HC_HASS_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeassistant.fullname" . }}-secret
                  key: api_key
            - name: HC_HASS_URL
              value: "http://{{ template "homeassistant.fullname" . }}:8123/api/"
            - name: HC_BASEPATH
              value: "/hass-config"
            - name: HC_GIT
              value: "false"
            - name: HC_ENFORCE_BASEPATH
              value: "true"
          ports:
            - name: http
              containerPort: 3218
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /hass-config
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.server.repository }}:{{ .Values.image.server.tag }}"
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
    {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
        {{- if .Values.persistentVolume.existingClaim -}}
          claimName: {{ .Values.persistentVolume.existingClaim }}
        {{ else }}
          claimName: {{ include "homeassistant.fullname" . }}
        {{- end }}
    {{ else }}
        emptyDir: {}
    {{- end }}
