apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homeassistant.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "homeassistant.name" . }}
    helm.sh/chart: {{ include "homeassistant.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.apiToken }}
  api_key: "{{ .Values.apiToken | b64enc }}"
  {{ else }}
  api_key: "{{ randAlphaNum 20 | b64enc }}"
  {{- end }}